on:
  workflow_dispatch:
  push:
    paths:
      - 'MyPortfolio/**'

- name: Restore NuGet packages
    shell: bash
    run: |
    dotnet restore .

- name: Build solution
    shell: bash
    run: |
    dotnet build . -c Release

- name: Test solution
    shell: bash
    run: |
    dotnet test . -c Release

- name: Publish artifact
    shell: bash
    run: |
    dotnet publish ./MyPortfolio -c Release -o published

- name: Set basepath on index.html
    shell: pwsh
    run: |
      $filepath = "./MyPortfolio/wwwroot/index.html"
      $repository = "${{ github.repository }}" -replace "${{ github.repository_owner }}", ""

      $html = Get-Content -Path $filepath
      $html -replace "<base href=`"/`" />", "<base href=`"$repository/`" />" | Out-File -Path $filepath -Force

- name: Set basepath on JSON objects
    shell: pwsh
    run: |
      $filepath = "./MyPortfolio/wwwroot/sample-data"
      $repository = "${{ github.repository }}" -replace "${{ github.repository_owner }}", ""

      Get-ChildItem -Path $filepath -Filter "*.json" | ForEach-Object {
          $json = Get-Content -Path $_.FullName
          $json.Replace("../", "$repository/") | Out-File -Path $_.FullName -Force
      }
